### ISSUE TITLE
cwd ignored when copying files

### ISSUE THREAD

**Issue by tinfoil-knight** [sindresorhus/cpy#107]
I recently migrated to the newer `v9.0.1` & updated some code as per: https://github.com/sindresorhus/cpy/releases/tag/v9.0.0

```
fixtures/directory/
└── test
    └── index.js
```

I'm trying to copy the `test` directory to some other temporary directory but only the `index.js` file gets copied directly without being under the `test` directory.

I've created a minimal reproduction here: https://github.com/KK-Learning-Gym/cpy-path-err.

Relevant lines are here: https://github.com/KK-Learning-Gym/cpy-path-err/blob/2140c4814dbf905d2bb6ed03354323fe22a69c12/index.mjs#L12-L20

I was trying to debug this a little bit. It seems like the `cwd` isn't considered under the `if (path.isAbsolute(destination))` here:

https://github.com/sindresorhus/cpy/blob/15f955745634516756309db332243e72ba10ba53/index.js#L96-L98

**Comment by mfukala** [comment]
Files from source directory are copied but to themselves (into their locations in source directory) instead of into dest directory. 

I had to work it around by prefixing patterns with the source directory like this:

```
await cpy([
    '*',
    'ignore*'
], dest, {
    cwd: source,
})
```

to 

```
await cpy([
    `${source}/*`,
    `!${source}/ignore*`
], dest,)
```

**Comment by danielweck** [comment]
I am experiencing the same bug with `cpy-cli` v5 but only in some cases ... very strange bug, yet 100% reproducible (I am trying to find out why ... seems related to CWD pointing to a subfolder inside the current folder, otherwise if it's a parent folder or the local root folder, then it works)

**Comment by danielweck** [comment]
Related issue? https://github.com/sindresorhus/cpy/issues/113

Seems to be hinting at the same code:
https://github.com/sindresorhus/cpy/blob/15f955745634516756309db332243e72ba10ba53/index.js#L96-L98

**Comment by danielweck** [comment]
Ah, I debugged `cpy` and I can see incorrect behaviour at this line:

https://github.com/sindresorhus/cpy/blob/38c5d858aa480015bcf15c0b5e493995a3f25ce3/index.js#L113C2-L113C2

I managed to create a minimal repro using the low-level NodeJS `path` API via the command line:

Assuming my CWD is `/absolute/folder/`:
```
node -e "const cwd='./'; const destination='../parent_folder/'; const entry='/absolute/folder/subfolder/file.txt'; const relative='subfolder/file.txt'; const path = require('path');console.log(path.join(cwd, destination, relative));"
```
=>
`../parent_folder/subfolder/file.txt`

Now assuming my CWD is `/absolute/`:
```
node -e "const cwd='./folder'; const destination='../parent_folder/'; const entry='/absolute/folder/subfolder/file.txt'; const relative='folder/subfolder/file.txt'; const path = require('path');console.log(path.join(cwd, destination, relative));"
```
`parent_folder/folder/subfolder/file.txt` (notice the missing `../` prefix)

In concrete terms, this fails in my project:

`cpy ./data/ ../target/ --cwd=./sub/` (`./sub/` contains `data/`)

... whereas this succeeds:

`cpy ./data/ ../parent/inner/" --cwd=./` (`./` contains `data/`)

**Comment by danielweck** [comment]
Ah, it's a regression in `cp-file`!

https://github.com/sindresorhus/cp-file/blob/v10.0.0/index.js#L104-L111

vs.

https://github.com/sindresorhus/cp-file/blob/v9.1.0/index.js#L90-L93

Note the added code:

```
if (options.cwd) {
  ({sourcePath, destinationPath} = resolvePath(options.cwd, sourcePath, destinationPath));
}
```

**Comment by danielweck** [comment]
My workaround / temporary fix is: add `cwd: null` immediately after the `...options` spread in the `copyFile()` call:

`await copyFile(entry.path, to, {...options, cwd: null, onProgress: fileProgressHandler});`
