### ISSUE TITLE
Can commonjs be supported

### ISSUE THREAD

**Issue by Jeffrey-mu** [sindresorhus/cpy#108]
My project environment is commonjs. I found that this package can solve my needs, but it doesn't seem to support cjs

If I can support it, I can submit pr

Thank you.

**Comment by sindresorhus** [comment]
No plans for that. You can use it with CommonJS by using `await import()`.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by Jeffrey-mu** [comment]
Okay, I'll try it. Thank you very much, sindresorhus @sindresorhus
