### ISSUE TITLE
Doesn’t overwrite in npm scripts

### ISSUE THREAD

**Issue by AntoineBoulanger** [sindresorhus/cpy#16]
When I run `cpy` from a `package.json` script, It only copies the file if it doesn't already exist. 
If the file exist, it doesn't overwrite, it does nothing. 

When I run the same line in the terminal, not from an npm script, it does overwrite.

**Comment by floatdrop** [comment]
@AntoineBoulanger could it be, that `cpy` versions are different? Overwritting from cli was fixed in #14.
