### ISSUE TITLE
Add option to ignore a file in the source files

### ISSUE THREAD

**Issue by ragingwind** [sindresorhus/cpy#17]
I would like to have an option to ignore some file in the source file list. Sometime I need to filter a file in the  source which I don't want to copy them to destination. So I added [code](https://github.com/ragingwind/cpy/blob/master/cli.js#L38) and [test](https://github.com/ragingwind/cpy/blob/master/test.js#L240)  for testing. As a result I think It's not bad. What do you think about?

**Comment by sindresorhus** [comment]
You can already do this with the negate glob pattern. See the readme example.

**Comment by ragingwind** [comment]
Yes, I can find the example using multiple glob pattern with apis. But I don't know that how to use multiple glob patterns by cli. :)

**Comment by sindresorhus** [comment]
Oh right, sorry. Can you do your changes in a PR, and I'll review? ;)

**Comment by ragingwind** [comment]
Ok, I will make a new PR for this.

**Comment by arthurvr** [comment]
Thanks @ragingwind :)

**Comment by schnittstabil** [comment]
Negation patterns are [deprecated](https://github.com/isaacs/node-glob#comments-and-negation), so I think we should introduce an `ignore` flag.

**Comment by schnittstabil** [comment]
Oh, I've forgotten that globby already [translates `!`-patterns to `ignore`](https://github.com/sindresorhus/globby/blob/master/index.js#L8)
