### ISSUE TITLE
Source paths always preserved

### ISSUE THREAD

**Issue by Flet** [sindresorhus/cpy#2]
Is this expected behavior for the CLI?

(at root of module)
```
flet@lappy:~/code/someproject$ ls assets/markup/
mock.html

flet@lappy:~/code/someproject$ cpy assets/markup/*.html dist

flet@lappy:~/code/someproject$ tree dist
dist
└── assets
    └── markup
        └── mock.html

```

I guess I was expecting it to work similarly to `cp` in linux?

```
flet@lappy:~/code/someproject$ cp assets/markup/*.html dist

flet@lappy:~/code/someproject$ tree dist
dist
└── mock.html
```

I realize this might not be the goal of this module and I'm prepared for this issue to be closed immediately :)

**Comment by sindresorhus** [comment]
Hmm, yeah, the thing is that both could be valid behaviour. Not sure which to pick too be honest.

Do you know where I read more about the `cp` glob behavior?

-

@contra What's the reason you went with `cp` like behaviour for gulp by setting base at the beginning of the glob?

**Comment by contra** [comment]
@sindresorhus Seemed like a good idea at the time, but it has created some confusion. Seemed more intuitive to me than specifying a root

**Comment by schnittstabil** [comment]
@sindresorhus `cp` doesn't care about the globbing - but the shell:
```bash
$ tree assets/
assets/
└── markup
    ├── mock2.html
    └── mock.html
$ echo assets/markup/*.html
assets/markup/mock2.html assets/markup/mock.html
```
That means `cp` get the same argument vector in the following examples:
```bash
cp assets/markup/*.html dist
cp assets/markup/mock2.html assets/markup/mock.html dist
```

**Comment by schnittstabil** [comment]
It seems that `cpy` is similar to `cp --parents`.

**Comment by kevva** [comment]
I'd vote for the same behavior as `cp`, i.e not creating paths, but having an option similar to `--parents`.

**Comment by sindresorhus** [comment]
:+1: Alright, let's go with that.

**Comment by schnittstabil** [comment]
I think being POSIX-compliant as far as practicable is reasonable for the `cli` and therefore think the `cp` behavior is a good choice.

But considering gulp, grunt and similar tasks, I think the `--parents` use case is the default for the API:
```javascript
cpy(['assets/**/*'], 'dist', {parents: true, nodir: true} , cb);
```

**Comment by Flet** [comment]
My interest is in using `cpy` as an OS agnostic copy command in npm scripts, so POSIX makes sense for my use case... If its not the default then having a flag to turn it off would work just as well.

**Comment by schnittstabil** [comment]
Overwriting the default settings within gulp etc. is rather simple. POSIX FTW!

**Comment by tobiastom** [comment]
Please remember to add this so the CLI as well. I'd like to copy a file to a specific location with a different name. When I understand this correctly it should work?

e.g.

```
cpy package.json Build/$npm_package_name-$npm_package_version.json
```

**Comment by schnittstabil** [comment]
@tobiastom Actually `cpy` presumes that the destination is a directory. This issue is about preserving the directory structure and won't affect your problem. You may want to create a new issue for that.

**Comment by tobiastom** [comment]
@schnittstabil Thanks for your comment. Just for reference: I did create »Copy separate file, with possible new name« (#6).
