### ISSUE TITLE
Promisify the API

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cpy#23]
Same as with https://github.com/sindresorhus/cp-file/commit/713bc19575467e5d698ebdb9ba2b885fd1f5641e.

Help welcome :)

**Comment by lukehorvat** [comment]
With or without adding another dependency? Because you could just [pify](https://github.com/sindresorhus/pify) the function before exporting it.

**Comment by sindresorhus** [comment]
@lukehorvat Same as https://github.com/sindresorhus/cp-file/commit/713bc19575467e5d698ebdb9ba2b885fd1f5641e, so using `pinkie-promise` as promise polyfill and using promises all over, not just pify the main export.
