### ISSUE TITLE
Create destination directory if doesn't exist?

### ISSUE THREAD

**Issue by dmitriz** [sindresorhus/cpy#28]
When no destination directory is present, the attempt to copy files there results in error:
```
CpyError: `src` and `dest` required
```

Is there any way to configure to have it instead created like e.g. the default `cp`?

**Comment by sindresorhus** [comment]
It already does that. Your error indicates you haven't specified the function arguments correctly.

**Comment by dmitriz** [comment]
Hm... I must be missing something.

Here is my directory:
```sh
→ ls
index.js     myfile       node_modules package.json
```
So the file `myfile` exists but not the directory `mydir`.
The node script:
```js
// index.js
const cpy = require('cpy')

const file = 'myfile'
const dest = 'mydir'

cpy(file, dest).then(() => {
    console.log(file, 'is copied to', dest)
})
.catch((e) => {
	console.error(file, 'is NOT copied to', dest, 'and we have error:', e)	
})
```
and the output:
```sh
→ node index.js 
myfile is NOT copied to mydir and we have error: { [CpyError: `src` and `dest` required] nested: undefined }
```
Any idea what the error means and why?

(PS. Thanks for the quick answer, much appreciated!)

**Comment by dmitriz** [comment]
I've looked at your tests and figured it out -- it seems like the file needs to be wrapped into array:
```js
// index.js
...
const files = ['myfile']
cpy(files, dest).then(() => {
    console.log(files, 'is copied to', dest)
})
```
```sh
→ node index.js 
[ 'myfile' ] 'is copied to' 'mydir'
```
Suggestion: 
Make the error message more descriptive like "First argument must be array"?

**Comment by kevva** [comment]
It's pretty obvious if you read the documentation `https://github.com/sindresorhus/cpy#files` :).

**Comment by dmitriz** [comment]
Agree. But the error message could be friendlier to those who don't read it. ;)

**Comment by sindresorhus** [comment]
There's a limit to how much handholding we should do, especially when users don't even bother reading the clear and short docs. That being said, PR welcome.

**Comment by dmitriz** [comment]
Thanks, good to know 😄 
https://github.com/sindresorhus/cpy/pull/29
