### ISSUE TITLE
Make use of `globby.generateGlobTasks`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/cpy#30]
// @schnittstabil

**Comment by sindresorhus** [comment]
@schnittstabil Do you remember why we wanted this? If yes, would you mind adding a description in case someone wants to complete this issue?

**Comment by schnittstabil** [comment]
It is needed to implement a `recursive` option. I've gave it a shot some time ago, but the limited ES2015 Promise interface leaded to very, very complicated code. Code that I don't want to be in charge of :wink:

I've noticed your awesome [promise-fun](https://github.com/sindresorhus/promise-fun) collection, hence than I wanted to make a new attempt. Sadly, I haven't found time yet…

**Comment by sindresorhus** [comment]
I would be ok with targeting Node.js 8 in a new major version so we could make use of async/await for this. That and in combination with using some `promise-fun` modules, should make this a lot easier to do.
