### ISSUE TITLE
arrify the `src` argument

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/cpy#31]
Would be nice just to specify a string instead of wrapping with an array

**Comment by sindresorhus** [comment]
I dunno. I kinda like strict types. But I don't feel very strongly about it.

You're the [second person to request it](https://github.com/sindresorhus/cpy/pull/29) now, so maybe it makes sense.

**Comment by jamestalmage** [comment]
>  I kinda like strict types.

Then you've invested in the wrong programming language 😉.

I can tell you I tried it before re-reading the docs. I don't see how it would create ambiguity.

If you are against it here, how is it different from situations where we do use it?

**Comment by sindresorhus** [comment]
True dat. Well, sure. If you care enough to do the change yourself, I'll merge ;)

-

> If you are against it here, how is it different from situations where we do use arrify?

I haven't been very consistent about it in the past. As you've said JS inherently isn't very strict.

**Comment by schnittstabil** [comment]
:+1: for [`arrify`](https://github.com/sindresorhus/arrify), single values are just degenerated arrays – aren't they? :stuck_out_tongue_winking_eye:

**Comment by sindresorhus** [comment]
@schnittstabil Feel free to do the change.
