### ISSUE TITLE
Doesn't copy "__"-prefixed files

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/cpy#41]
```js
cpy("path/to/__*.ext", destination)
```
doesn't copy, and throws no errors.

With the files renamed, this copies just fine:
```js
cpy("path/to/_*.ext", destination)
```

**Comment by schnittstabil** [comment]
Sorry, I'm unable to reproduce that. Are you sure `path/to/__file` exists? Which OS, node version and cpy version do you use?

**Comment by stevenvachon** [comment]
Yes, it existed. MacOS Sierra, Node 7.3.0, cpy 5.0.0

I tested the "__" prefixes with [glob](https://npmjs.com/blog) and they resolved, so I know that isn't to blame.

I've switched my project to use "_" prefixes for now.

**Comment by schnittstabil** [comment]
Sadly, I'm on Linux – which shouldn't matter. I could imagine that this issue is related to your concrete paths; hence, would you mind to share the full path of the sources and the `destination`? – as far as I remember, `cpy` uses the [_realpath_](https://nodejs.org/api/fs.html#fs_fs_realpath_path_options_callback).

**Comment by stevenvachon** [comment]
/Users/stevendvachon/ProjectName/test/fixtures/__test.html.hbs

"ProjectName" is a substitute, but the real name has the same casing and no spaces.

**Comment by schnittstabil** [comment]
@stevenvachon Sorry, I run out of ideas. My last one:

`cpy` uses [`globby`](https://github.com/sindresorhus/globby) internally; thus, you may try:

```js
const globby = require('globby');
…
console.log(globby.sync("path/to/__*.ext"));
cpy("path/to/__*.ext", destination);
```

This outputs the files `cpy` will to try to copy; and therefore, will show if we are dealing with a globbing or a copying issue.

**Comment by sindresorhus** [comment]
Closing for lack of response by OP.

**Comment by stevenvachon** [comment]
Sorry. This was so long ago that I no longer have the details.
