### ISSUE TITLE
Rename option with glob

### ISSUE THREAD

**Issue by amk221** [sindresorhus/cpy#51]
With:

```javascript
cpy('src/**/*.{js,css}', 'dest', { parents: true, rename: 'foo' });
```
I was expecting the `src` directory to be renamed to `foo` (perhaps unreasonably?)

```
dest/
  |
  + foo/
     |
     + file.js
     + file.css
```

But in fact, I get

```
dest/
  |
  + file.js
  + file.css
  + foo
```

**Comment by sindresorhus** [comment]
That's not how the `rename` option works:

> Filename or function returning a filename used to rename **every file in files**.

Passing a string is only really useful when there's only one file. With many files, you'll have to use a function and handle it manually.
