### ISSUE TITLE
Copy folder and preserve folder structure of the copied folder only

### ISSUE THREAD

**Issue by radum** [sindresorhus/cpy#55]
If we have the following tree:

```
src
  static
    images
      img1.jpg
      img2.jpg
    file1.txt
  ignoreme.txt
```

If I want to copy this entire folder contents of `src/static` to `build/static` and keep the folder structure, as far as I can tell there is no way to do it with this module. Using `parents` will also move `src` into `build` folder.

Adding `cwd` to the mix will pass the same option to dest parameter so instead of moving files to `build` folder it will copy them to `src/build/...`.

Am I missing anything? Is there a way to copy a folder contests and preserve the contents folder structure to another destination?

**Comment by RebeccaStevens** [comment]
It's kind of ugly but you can use both `parents` and `cwd` with absolute paths:

```js
{
  files: 'static/**/*',
  dest: path.join(process.cwd(), 'build'),
  options: {
    cwd: path.join(process.cwd(), 'src'),
    parents: true
  }
}
```

**Comment by radum** [comment]
Thanks @RebeccaStevens :) 🌷
