### ISSUE TITLE
The file doesn't exist, even though it does

### ISSUE THREAD

**Issue by anogr** [sindresorhus/cpy#72]
If I try to copy a folder using cpy-cli, I get an error message saying the file doesn't exist. The "file" is a folder, and it does exist.

The error is in index.js, line 81. I don't know the intent of the check
!sourcePaths.every(value => files.includes(value))
but that's the reason it fails.

That check was added September 22.

**Comment by sindresorhus** [comment]
// @whitecrownclown

**Comment by smileLilith** [comment]
I've faced the same issue when I've tried to copy directory that exists.
```
(node:35974) UnhandledPromiseRejectionWarning: NestedError: Cannot copy `node_modules/@fortawesome/fontawesome-free/webfonts`: the file doesn't exist
    at promise (/<my-project-path>/node_modules/cpy/index.js:76:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:35974) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35974) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Downgrading to v7.3.0 fix the issue.

**Comment by whitecrownclown** [comment]
// @sindresorhus 

The issue introduced [here](https://github.com/sindresorhus/cpy/pull/68) is that we cannot differentiate between folders & files without reading the fs. (afaik)

The `!sourcePaths.every(value => files.includes(value))` check would verify the returned files from `globby` with the provided `source` (excluding globs). However, directories are listed in the `source`, but not in the `files` output and the check would fail.

I think we should revert to only throwing an error when `files.length === 0`.

**Comment by taion** [comment]
ref https://github.com/sindresorhus/cpy/pull/74 – that check had some other problems, too

**Comment by sindresorhus** [comment]
@whitecrownclown Yeah, lets do that.
