### ISSUE TITLE
Strange behavior on latest `recursive` mode

### ISSUE THREAD

**Issue by JounQin** [sindresorhus/cpy#91]
I installed latest `cpy` with `yarn add cpy@sindresorhus/cpy`.

```js
// copy.js

// @ts-check

import cpy from 'cpy'

const args = process.argv.slice(2)

cpy(args, args.pop())
```

```sh
node copy 'node_modules/shiki/{dist/*.wasm,languages,themes}/**' public/shiki
```

![image](https://user-images.githubusercontent.com/8336744/132080295-775b9289-60f4-475b-9b4d-093fb862534b.png)

```sh
node copy 'node_modules/shiki/{dist/*.wasm,languages,themes}/**' public/shiki/_ # note the `/_` here
```

![image](https://user-images.githubusercontent.com/8336744/132080335-4f66d9cb-6599-453a-9161-a93a8e696f39.png)

I also tried the following one and it failed.

```sh
node copy 'node_modules/shiki/{dist/*.wasm,languages/**,themes/**}' public/shiki
```

But the following one also worked

```sh
node copy 'node_modules/shiki/{dist/*.wasm,languages/**,themes/**}' public/shiki/_
```

**Comment by JounQin** [comment]
cc @Idered

**Comment by Idered** [comment]
@JounQin I found the issue and I'm working on solution
