### ISSUE TITLE
Wrong dependencies resolution

### ISSUE THREAD

**Issue by matteodisabatino** [sindresorhus/cpy#94]
According to package.json the dependencies list is:

```js
{
  "dependencies": {
    "arrify": "^3.0.0",
    "cp-file": "^9.1.0",
    "globby": "^12.0.0",
    "junk": "^3.1.0",
    "nested-error-stacks": "^2.1.0",
    "p-filter": "^2.1.0",
    "p-map": "^5.0.0"
}
```

However checking against my package-lock.json, cpy resolves dependencies like so:

<img width="565" alt="Schermata 2021-10-12 alle 21 58 53" src="https://user-images.githubusercontent.com/4496968/137021080-c77a6c0e-9ced-495c-a289-c2aaf4ecf5da.png">

As shown, almost all packages are resolved with a version different than the one in the package.json and I can't figure out why. Could someone explain?

**Comment by sibiraj-s** [comment]
You are comparing master with last published version which is like 8 months ago. Hence the difference,

**Comment by matteodisabatino** [comment]
Got it, thanks for the answer.
